-- ตำแหน่งของเที่ยวระหว่างวิ่ง
--
-- เดิมรู้แค่ว่า "ส่งจุดนี้แล้ว" กับพิกัดตอนเก็บ POD หนึ่งจุดต่อหนึ่งใบ ระหว่างทางมืดสนิท
-- คนวางแผนตอบลูกค้าไม่ได้ว่ารถอยู่ไหน และเวลามีข้อโต้แย้งก็ไม่มีอะไรยืนยัน
--
-- ขอบเขตที่ตั้งใจ:
--  * บันทึกตั้งแต่คนขับกดรับงาน ไม่ใช่ตลอดเวลา — นอกเวลางานไม่ใช่เรื่องของระบบนี้
--  * เก็บ 30 วันแล้วลบทิ้งอัตโนมัติ พอสำหรับเคลมของหายและข้อโต้แย้งการส่ง
--    เก็บนานกว่านั้นคือเก็บประวัติการเดินทางของพนักงานโดยไม่มีใครใช้
--  * คนขับเปิดดูเส้นทางของตัวเองได้ เป็นเรื่องความเป็นธรรม ไม่ใช่การจับตาข้างเดียว

create table if not exists public.trip_locations (
  id          bigint generated by default as identity primary key,
  trip_id     bigint not null references public.trips (id) on delete cascade,
  driver_id   bigint references public.drivers (id) on delete set null,
  lat         double precision not null,
  lng         double precision not null,
  /* ความแม่นเป็นเมตรจากอุปกรณ์ — จุดที่แม่น 2 กม. กับจุดที่แม่น 5 เมตร
     ห้ามวาดเท่ากันบนแผนที่ ไม่งั้นคนอ่านจะเชื่อจุดที่ไม่ควรเชื่อ */
  accuracy_m  double precision,
  recorded_at timestamptz not null default now()
);

create index if not exists trip_locations_trip_idx
  on public.trip_locations (trip_id, recorded_at desc);
create index if not exists trip_locations_recorded_idx
  on public.trip_locations (recorded_at);

alter table public.trip_locations enable row level security;

drop policy if exists trip_locations_read on public.trip_locations;
create policy trip_locations_read on public.trip_locations
  for select using (
    app.has_perm('dispatch.view')
    or driver_id = app.current_driver_id()
    or exists (select 1 from public.trip_drivers td
                where td.trip_id = trip_locations.trip_id
                  and td.driver_id = app.current_driver_id())
  );

/* เขียนผ่าน RPC เท่านั้น — จุดที่ปักเองได้ตามใจไม่ใช่หลักฐาน */
drop policy if exists trip_locations_write on public.trip_locations;
create policy trip_locations_write on public.trip_locations
  for all using (false) with check (false);

/* ลบของเก่าเกิน 30 วัน — ไม่มี pg_cron ในโปรเจกต์นี้ จึงเรียกแบบสุ่มจากตัวบันทึกเอง
   ประมาณหนึ่งครั้งต่อร้อยจุด ซึ่งพอสำหรับปริมาณระดับกองรถสิบคัน
   และไม่ทำให้การบันทึกจุดกลายเป็นงานหนักทุกครั้ง */
create or replace function app.purge_old_trip_locations()
returns integer
language sql
security definer
set search_path to 'public'
as $function$
  with gone as (
    delete from public.trip_locations
     where recorded_at < now() - interval '30 days'
    returning 1
  )
  select count(*)::int from gone;
$function$;

create or replace function public.log_trip_location(
  p_trip_id bigint,
  p_lat double precision,
  p_lng double precision,
  p_accuracy_m double precision default null
)
returns void
language plpgsql
security definer
set search_path to 'public', 'auth'
as $function$
declare
  v_me   bigint := app.current_driver_id();
  v_trip public.trips;
begin
  if not app.has_perm('myjobs.progress') then
    raise exception 'ไม่มีสิทธิ์อัปเดตงาน' using errcode = '42501';
  end if;

  select * into v_trip from public.trips where id = p_trip_id;
  if not found then
    raise exception 'ไม่พบเที่ยวนี้' using errcode = 'P0002';
  end if;

  if v_trip.driver_id is distinct from v_me
     and not exists (select 1 from public.trip_drivers td
                      where td.trip_id = p_trip_id and td.driver_id = v_me) then
    raise exception 'เที่ยวนี้ไม่ใช่งานของคุณ' using errcode = '42501';
  end if;

  /* บันทึกเฉพาะช่วงที่งานเดินอยู่จริง: รับงานแล้ว และยังไม่ปิด
     เที่ยวที่จบแล้วยังส่งจุดเข้ามาได้แปลว่ามีแอปค้างอยู่ในมือถือใครสักคน */
  if v_trip.accepted_at is null or v_trip.status in ('completed', 'cancelled') then
    return;
  end if;

  insert into public.trip_locations (trip_id, driver_id, lat, lng, accuracy_m)
  values (p_trip_id, v_me, p_lat, p_lng, p_accuracy_m);

  if random() < 0.01 then
    perform app.purge_old_trip_locations();
  end if;
end;
$function$;

grant execute on function public.log_trip_location(bigint, double precision, double precision, double precision) to authenticated;

/* ตำแหน่งล่าสุดของทุกเที่ยวที่กำลังวิ่ง — หน้าติดตามใช้ตัวนี้ตัวเดียว
   ส่งจุดส่งที่เหลือมาด้วย เพราะแผนที่ที่มีแต่รถแต่ไม่มีปลายทางตอบอะไรไม่ได้ */
create or replace function public.tracking_board()
returns json
language sql
stable security definer
set search_path to 'public', 'auth'
as $function$
  select coalesce(json_agg(x order by x.trip_no), '[]'::json)
    from (
      select t.id as trip_id,
             t.trip_no,
             t.status,
             t.departed_at,
             v.plate_no,
             (select string_agg(d.name, ', ' order by td.seq)
                from public.trip_drivers td
                join public.drivers d on d.id = td.driver_id
               where td.trip_id = t.id) as drivers,
             (select json_build_object('lat', l.lat, 'lng', l.lng,
                                       'accuracy_m', l.accuracy_m,
                                       'recorded_at', l.recorded_at)
                from public.trip_locations l
               where l.trip_id = t.id
               order by l.recorded_at desc
               limit 1) as last_seen,
             (select count(*) from public.orders o
               where o.trip_id = t.id and o.status = 'delivered') as stops_done,
             (select count(*) from public.orders o where o.trip_id = t.id) as stops_total,
             (select coalesce(json_agg(json_build_object(
                       'order_id', p.order_id, 'lat', p.lat, 'lng', p.lng,
                       'collected_at', p.collected_at) order by p.collected_at), '[]'::json)
                from public.pod p
                join public.orders o on o.id = p.order_id
               where o.trip_id = t.id and p.lat is not null) as pod_points
        from public.trips t
        join public.vehicles v on v.id = t.vehicle_id
       where t.status in ('planned', 'in_progress')
         and (app.has_perm('dispatch.view')
              or t.driver_id = app.current_driver_id()
              or exists (select 1 from public.trip_drivers td
                          where td.trip_id = t.id
                            and td.driver_id = app.current_driver_id()))
    ) x;
$function$;

grant execute on function public.tracking_board() to authenticated;

/* เส้นทางของเที่ยวเดียว — ดึงตอนกดเลือกคันบนแผนที่ ไม่ได้โหลดมาทั้งหมดตั้งแต่แรก
   จุดหนึ่งวันของรถหนึ่งคันมีหลักพัน โหลดพร้อมกันทุกคันคือหน้าค้าง */
create or replace function public.trip_track(p_trip_id bigint)
returns json
language sql
stable security definer
set search_path to 'public', 'auth'
as $function$
  select coalesce(json_agg(json_build_object(
           'lat', l.lat, 'lng', l.lng,
           'accuracy_m', l.accuracy_m,
           'recorded_at', l.recorded_at) order by l.recorded_at), '[]'::json)
    from public.trip_locations l
    join public.trips t on t.id = l.trip_id
   where l.trip_id = p_trip_id
     and (app.has_perm('dispatch.view')
          or t.driver_id = app.current_driver_id()
          or exists (select 1 from public.trip_drivers td
                      where td.trip_id = t.id
                        and td.driver_id = app.current_driver_id()));
$function$;

grant execute on function public.trip_track(bigint) to authenticated;
