-- หลักฐานการส่งมอบเก็บรูปได้รูปเดียว
--
-- pod.photo_path เป็นคอลัมน์เดี่ยว คนขับจึงเลือกได้อย่างเดียวว่าจะถ่ายอะไร
-- ทั้งที่ข้อโต้แย้งเรื่องการส่งของต้องการหลายมุมพร้อมกัน: ของที่ส่ง สภาพหน้าร้าน
-- ใบเซ็นรับ และป้ายทะเบียนรถที่ไปส่ง รูปเดียวตอบได้แค่ข้อเดียว
--
-- เก็บรูปเป็นแถว ไม่ใช่คอลัมน์ ทำให้เพิ่มมุมใหม่ทีหลังได้โดยไม่ต้องแก้ตารางอีก
-- คอลัมน์ photo_path เดิมคงไว้ ไม่ลบ — เป็นรูปหลักที่ใช้แสดงย่อในรายการ
-- และของเก่าที่เคยเก็บไว้ยังอ่านได้เหมือนเดิม

create table if not exists public.pod_photos (
  id         bigint generated by default as identity primary key,
  pod_id     bigint not null references public.pod (id) on delete cascade,
  path       text   not null,
  /* มุมของรูป — คนดูย้อนหลังต้องรู้ว่ารูปนี้ถ่ายอะไร ไม่ใช่เดาจากภาพ
     ปล่อยเป็น text ไม่ใช่ enum เพราะรายการมุมจะเพิ่มตามหน้างาน ไม่ควรต้อง migrate ทุกครั้ง */
  kind       text   not null default 'other',
  created_at timestamptz not null default now()
);

create index if not exists pod_photos_pod_idx on public.pod_photos (pod_id);

alter table public.pod_photos enable row level security;

drop policy if exists pod_photos_read on public.pod_photos;
create policy pod_photos_read on public.pod_photos
  for select using (
    app.has_perm('pod.view')
    /* คนขับต้องเปิดดูรูปของงานตัวเองได้ ทั้งคนขับหลักและคนที่ไปด้วย */
    or exists (
      select 1
        from public.pod p
        join public.orders o on o.id = p.order_id
        join public.trips t on t.id = o.trip_id
       where p.id = pod_photos.pod_id
         and (t.driver_id = app.current_driver_id()
              or exists (select 1 from public.trip_drivers td
                          where td.trip_id = t.id
                            and td.driver_id = app.current_driver_id()))
    )
  );

/* เขียนผ่าน RPC เท่านั้น — การแนบรูปเข้าหลักฐานต้องผ่านด่านเดียวกับการบันทึก POD
   ไม่งั้นใครที่ล็อกอินได้ก็แนบรูปเข้าหลักฐานของคนอื่นได้ */
drop policy if exists pod_photos_write on public.pod_photos;
create policy pod_photos_write on public.pod_photos
  for all using (app.has_perm('pod.write')) with check (app.has_perm('pod.write'));

-- ของเก่า: รูปเดี่ยวที่เคยเก็บไว้ ย้ายมาเป็นแถวแรกของหลักฐานใบนั้น
insert into public.pod_photos (pod_id, path, kind, created_at)
select p.id, p.photo_path, 'goods', p.collected_at
  from public.pod p
 where coalesce(btrim(p.photo_path), '') <> ''
   and not exists (select 1 from public.pod_photos x where x.pod_id = p.id);

/* บันทึกหลักฐานพร้อมรูปหลายใบในจังหวะเดียว
   แยกเป็นสองคำสั่งไม่ได้ — ถ้าบันทึก POD ผ่านแล้วแนบรูปล้ม จะเหลือหลักฐานที่อ้างว่า
   มีรูปแต่ไม่มีรูปจริง ซึ่งแย่กว่าหลักฐานที่ไม่มีรูปเลย

   p_photos เป็น jsonb array ของ { path, kind } */
create or replace function public.save_pod_with_photos(
  p_order_id bigint,
  p_recipient_name text,
  p_signature_data text,
  p_photos jsonb default '[]'::jsonb,
  p_notes text default null,
  p_lat double precision default null,
  p_lng double precision default null
)
returns bigint
language plpgsql
security definer
set search_path to 'public', 'auth'
as $function$
declare
  v_id    bigint;
  v_first text;
begin
  select nullif(btrim(e->>'path'), '') into v_first
    from jsonb_array_elements(coalesce(p_photos, '[]'::jsonb)) as x(e)
   limit 1;

  /* ด่านสิทธิ์ทั้งหมดอยู่ใน save_pod อยู่แล้ว เรียกต่อ ไม่เขียนกฎซ้ำสองที่ */
  v_id := public.save_pod(
    p_order_id, p_recipient_name, p_signature_data,
    v_first, p_notes, p_lat, p_lng
  );

  /* บันทึกซ้ำใบเดิม = แทนที่ชุดรูปทั้งชุด ไม่ใช่สะสมของเก่าปนของใหม่
     (POD ที่ยืนยันแล้วแก้ไม่ได้อยู่แล้ว — save_pod โยน error ก่อนถึงบรรทัดนี้) */
  delete from public.pod_photos where pod_id = v_id;

  insert into public.pod_photos (pod_id, path, kind)
  select v_id,
         nullif(btrim(e->>'path'), ''),
         coalesce(nullif(btrim(e->>'kind'), ''), 'other')
    from jsonb_array_elements(coalesce(p_photos, '[]'::jsonb)) as x(e)
   where nullif(btrim(e->>'path'), '') is not null;

  return v_id;
end;
$function$;

grant execute on function public.save_pod_with_photos(bigint, text, text, jsonb, text, double precision, double precision) to authenticated;

/* รูปทั้งชุดของใบหนึ่ง — ใช้ทั้งฝั่งคนขับและฝั่งออฟฟิศ */
create or replace function public.pod_photos_of_order(p_order_id bigint)
returns json
language sql
stable security definer
set search_path to 'public', 'auth'
as $function$
  select coalesce(json_agg(json_build_object('path', f.path, 'kind', f.kind)
                           order by f.id), '[]'::json)
    from public.pod_photos f
    join public.pod p on p.id = f.pod_id
    join public.orders o on o.id = p.order_id
    join public.trips t on t.id = o.trip_id
   where p.order_id = p_order_id
     and (app.has_perm('pod.view')
          or t.driver_id = app.current_driver_id()
          or exists (select 1 from public.trip_drivers td
                      where td.trip_id = t.id
                        and td.driver_id = app.current_driver_id()));
$function$;

grant execute on function public.pod_photos_of_order(bigint) to authenticated;
