-- หลักฐานที่ยืนยันไม่ได้ ลบได้เงียบ ๆ และรูปที่ไม่มีใครลบ
--
-- สามเรื่องที่โผล่มาพร้อมกันตอนไล่ว่าทำไมหน้าออเดอร์ไม่ขึ้นลายเซ็น:
--
-- 1) POD ค้างที่ 'collected' ตลอดกาล
--    สิทธิ์ pod.verify มี นโยบาย pod_update รองรับ แต่ฝั่งคลาวด์ไม่มีทางเรียกใช้
--    ปุ่มยืนยันตัวเดียวที่เคยมีอยู่ใน PodModal ซึ่งยิง PATCH /pod/:id/verify ของ
--    Express บน LAN — endpoint ที่ production ไม่มี ผลคือกฎ "หลักฐานที่ยืนยันแล้ว
--    แก้ไม่ได้" ที่เขียนไว้ใน save_pod ไม่เคยทำงานเลยสักครั้ง เพราะไม่มีใบไหน
--    ไปถึงสถานะนั้นได้ ทุกใบจึงเขียนทับได้ตลอดไป
--
-- 2) ลบเที่ยว = ลบหลักฐานถาวร โดยไม่เหลือร่องรอย
--    admin_force_delete_trip ลบแถว pod ทิ้งจริง ๆ (ตอนเริ่มไล่เรื่องนี้ ตาราง pod
--    ว่างเปล่าทั้งตาราง ทั้งที่คนขับเคยเซ็นแล้ว — นี่คือทางที่มันหายไป)
--    ปุ่มนี้มีไว้เก็บกวาดข้อมูลทดสอบ แต่ฐานไม่ได้แยกแยะว่าใบไหนทดสอบใบไหนของจริง
--    อย่างน้อยที่สุด ใบที่มีคนยืนยันแล้วต้องลบไม่ได้ และการลบทุกครั้งต้องมีบันทึก
--
-- 3) รูปในถังไม่เคยถูกลบ
--    pod_photos หายตาม pod (cascade) แต่ไฟล์จริงในถัง pod-photos ยังอยู่ครบ
--    ไม่มีโค้ดตรงไหนเรียก storage remove เลยสักที่ ผลคือรูปหน้าร้าน ใบเซ็นรับ
--    และของลูกค้าค้างสะสมอยู่ในถังไปเรื่อย ๆ โดยไม่มีใครรู้ว่ามีอะไรอยู่บ้าง
--    ลบจากฝั่ง SQL ไม่ได้ผลจริง (แถวใน storage.objects หายแต่ไฟล์ไม่หาย)
--    ทางที่ได้ผลคือให้ RPC คืน path ที่เพิ่งกำพร้าออกมา แล้วให้ฝั่งเว็บสั่งลบต่อ

/* ---------- 1) บันทึกการยุ่งกับหลักฐาน ---------- */

-- แยกจาก permission_audit_log เพราะคนละเรื่องกัน ตัวนั้นตอบว่า "ใครได้สิทธิ์อะไร"
-- ตัวนี้ตอบว่า "หลักฐานหายไปไหน" ซึ่งเป็นคำถามที่จะถูกถามตอนมีข้อโต้แย้งกับลูกค้า
create table if not exists public.evidence_audit_log (
  id           bigint generated by default as identity primary key,
  actor_user_id bigint references public.users(id) on delete set null,
  action       text not null,
  trip_no      text,
  order_id     bigint,
  pod_id       bigint,
  detail       json,
  created_at   timestamptz not null default now()
);

create index if not exists evidence_audit_created_idx on public.evidence_audit_log (created_at desc);

alter table public.evidence_audit_log enable row level security;

/* อ่านได้เฉพาะแอดมิน และไม่มีนโยบายเขียนเลยสักตัว — แถวเข้ามาได้ทางเดียวคือ
   ผ่านฟังก์ชัน security definer ข้างล่าง ใครลบหลักฐานแล้วลบบันทึกตามไม่ได้ */
drop policy if exists evidence_audit_admin_read on public.evidence_audit_log;
create policy evidence_audit_admin_read on public.evidence_audit_log
  for select to authenticated
  using (exists (select 1 from public.users u
                  where u.auth_id = auth.uid() and u.role = 'admin' and u.is_active));

/* ---------- 2) ยืนยันหลักฐาน ---------- */

create or replace function public.verify_pod(p_pod_id bigint)
returns json
language plpgsql
security definer
set search_path to 'public', 'auth'
as $fn$
declare
  v_pod public.pod;
begin
  if not app.has_perm('pod.verify') then
    raise exception 'ไม่มีสิทธิ์ยืนยันหลักฐานการส่งมอบ' using errcode = '42501';
  end if;

  select * into v_pod from public.pod where id = p_pod_id for update;
  if not found then
    raise exception 'ไม่พบหลักฐานใบนี้' using errcode = 'P0002';
  end if;

  /* ยืนยันซ้ำไม่ใช่ error — คนสองคนกดพร้อมกันจากคนละหน้าจอเกิดขึ้นได้จริง
     และผลลัพธ์ที่ได้ก็ตรงกับที่ทั้งคู่ต้องการอยู่แล้ว บอกไปตรง ๆ ว่ายืนยันแล้ว */
  if v_pod.status = 'verified' then
    return json_build_object('id', v_pod.id, 'status', 'verified', 'already', true);
  end if;

  update public.pod set status = 'verified', updated_at = now() where id = p_pod_id;

  insert into public.evidence_audit_log (actor_user_id, action, order_id, pod_id, detail)
  values (app.current_user_id(), 'pod_verified', v_pod.order_id, v_pod.id,
          json_build_object('recipient_name', v_pod.recipient_name));

  return json_build_object('id', v_pod.id, 'status', 'verified', 'already', false);
end;
$fn$;

grant execute on function public.verify_pod(bigint) to authenticated;

/* ---------- 3) ลบเที่ยวถาวร: กันหลักฐานที่ยืนยันแล้ว + บันทึก + คืน path รูป ---------- */

create or replace function public.admin_force_delete_trip(p_trip_id bigint)
returns json
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_trip      public.trips;
  v_pods      int := 0;
  v_verified  int := 0;
  v_orders    int := 0;
  v_bills     int := 0;
  v_tms_trips int := 0;
  v_tms_ids   uuid[];
  v_paths     text[];
begin
  if not app.has_perm('users.manage') then
    raise exception 'เฉพาะผู้ดูแลระบบเท่านั้นที่ลบเที่ยวถาวรได้' using errcode = '42501';
  end if;

  select * into v_trip from public.trips where id = p_trip_id for update;
  if not found then
    raise exception 'ไม่พบเที่ยวนี้' using errcode = 'P0002';
  end if;

  select count(*), count(*) filter (where p.status = 'verified')
    into v_pods, v_verified
    from public.pod p join public.orders o on o.id = p.order_id
   where o.trip_id = p_trip_id;

  /* ประตูใหม่ — ใบที่มีคนยืนยันแล้วคือใบที่ออฟฟิศรับรองว่าใช้ตอบลูกค้าได้
     ปุ่มที่มีไว้เก็บกวาดข้อมูลทดสอบ ไม่ควรลบของแบบนั้นได้เลยไม่ว่าใครกด
     ต้องยกเลิกการยืนยันก่อนถ้าจะลบจริง ซึ่งเป็นการตัดสินใจคนละอันกับการกดลบ */
  if v_verified > 0 then
    raise exception 'เที่ยวนี้มีหลักฐานที่ยืนยันแล้ว % ใบ ลบถาวรไม่ได้', v_verified
      using errcode = 'P0001';
  end if;

  /* เก็บ path ของรูปไว้ก่อนแถวจะหาย — ลบ storage.objects จากใน SQL ไม่ทำให้ไฟล์จริง
     หายไปด้วย ต้องให้ฝั่งที่มี session ของผู้ใช้เป็นคนสั่งลบผ่าน storage API */
  select array_agg(f.path) into v_paths
    from public.pod_photos f
    join public.pod p on p.id = f.pod_id
    join public.orders o on o.id = p.order_id
   where o.trip_id = p_trip_id;

  select array_agg(distinct t.tms_id) into v_tms_ids
    from public.tms_trips t
   where t.trip_id = p_trip_id;

  /* ใบดิบก่อนเสมอ — ทุกใบที่ชี้มาที่ออเดอร์ของเที่ยวนี้ บวกทุกใบของเที่ยวดิบเดียวกัน */
  delete from public.tms_shipments s
   where s.order_id in (select o.id from public.orders o where o.trip_id = p_trip_id)
      or (v_tms_ids is not null and s.tms_trip_id = any(v_tms_ids));
  get diagnostics v_bills = row_count;

  if v_tms_ids is not null then
    delete from public.tms_trips where tms_id = any(v_tms_ids);
    get diagnostics v_tms_trips = row_count;
  end if;

  /* pod_photos หายเองตาม pod (cascade) เช่นเดียวกับ order_items / trip_drivers /
     trip_locations ที่ผูกกับ orders / trips แบบ cascade อยู่แล้ว */
  delete from public.pod p using public.orders o
   where o.id = p.order_id and o.trip_id = p_trip_id;

  delete from public.orders where trip_id = p_trip_id;
  get diagnostics v_orders = row_count;

  delete from public.trips where id = p_trip_id;

  if v_pods > 0 then
    insert into public.evidence_audit_log (actor_user_id, action, trip_no, detail)
    values (app.current_user_id(), 'pod_deleted_with_trip', v_trip.trip_no,
            json_build_object('pods', v_pods, 'orders', v_orders,
                              'photos', coalesce(array_length(v_paths, 1), 0)));
  end if;

  return json_build_object(
    'trip_no', v_trip.trip_no,
    'deleted_orders', v_orders,
    'deleted_pods', v_pods,
    'deleted_tms_trips', v_tms_trips,
    'deleted_tms_bills', v_bills,
    /* ฝั่งเว็บเอาไปสั่งลบไฟล์ต่อ — ลบพลาดก็แค่เหลือไฟล์กำพร้าเท่าเดิม ไม่ย้อนกลับมา
       ทำให้ข้อมูลในฐานผิด จึงไม่ต้องอยู่ในทรานแซกชันเดียวกัน */
    'orphan_photo_paths', coalesce(to_json(v_paths), '[]'::json)
  );
end;
$fn$;

grant execute on function public.admin_force_delete_trip(bigint) to authenticated;

/* ---------- 4) ให้ลบไฟล์ในถังได้ ---------- */

/* ถังยังเป็น private เหมือนเดิม ที่เพิ่มคือสิทธิ์ "ลบ" ให้คนที่ถือ pod.write
   ซึ่งเป็นคนกลุ่มเดียวกับที่ลบเที่ยวถาวรได้อยู่แล้ว ไม่ได้เปิดให้ใครใหม่
   ไม่มีนโยบายนี้ = สั่งลบจากฝั่งเว็บแล้วเงียบ ไฟล์ยังอยู่ครบเหมือนเดิม */
drop policy if exists pod_photos_object_delete on storage.objects;
create policy pod_photos_object_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'pod-photos' and app.has_perm('pod.write'));
