-- เลขไมล์ตอนเริ่มวัน กับค่าทางด่วนตอนจบวัน — สองตัวเลขที่มีแต่คนขับเท่านั้นที่รู้
--
-- ทั้งคู่เก็บจากคนขับเพราะไม่มีทางอื่นที่ได้มา: เลขไมล์อยู่บนหน้าปัดรถ ค่าทางด่วน
-- อยู่บนใบเสร็จในมือคนขับ ออฟฟิศกรอกให้ไม่ได้ ได้แค่โทรถาม ซึ่งคือสิ่งที่ทำอยู่ทุกวัน
--
-- ทำไมเลขไมล์ถามวันละครั้ง ไม่ใช่ทุกเที่ยว — รถคันเดียวกันวิ่งหลายเที่ยวต่อวัน
-- ถามทุกเที่ยวคือถามคำถามเดิมซ้ำในเรื่องที่เปลี่ยนแปลงต่อเนื่อง แล้วได้เลขที่คนขับ
-- เดาเอาเพราะรำคาญ วันละครั้งตอนเริ่มงานคือจังหวะเดียวที่คนขับยืนอยู่หน้ารถจริง

/* จอคนขับต้องรู้ว่ากำลังขับรถคันไหนถึงจะถามเลขไมล์ได้ — view เดิมมีแต่ทะเบียน
   ซึ่งเอาไปเป็นกุญแจไม่ได้ ทะเบียนซ้ำกันได้เมื่อรถถูกขายแล้วป้ายถูกใช้ต่อ */
create or replace view public.my_trips as
  select t.id, t.trip_no, t.status, t.departed_at, t.arrived_at, t.notes,
         v.plate_no, v.vehicle_type,
         t.accepted_at, t.issue_note, t.issue_at,
         (select td.accepted_at from public.trip_drivers td
           where td.trip_id = t.id and td.driver_id = app.current_driver_id()) as my_accepted_at,
         (t.driver_id = app.current_driver_id()) as is_primary,
         (select count(*)::int from public.trip_drivers td where td.trip_id = t.id) as driver_count,
         (select count(*)::int from public.trip_drivers td
           where td.trip_id = t.id and td.accepted_at is not null) as accepted_count,
         (select tt.warehouse_code from public.tms_trips tt where tt.trip_id = t.id limit 1) as warehouse_code,
         (select tt.area from public.tms_trips tt where tt.trip_id = t.id limit 1) as area,
         /* ต่อท้ายเท่านั้น — แทรกกลางลิสต์แล้ว create or replace view ล้มทั้งคำสั่ง */
         t.vehicle_id
    from public.trips t
    join public.vehicles v on v.id = t.vehicle_id
   where app.has_perm('myjobs.view')
     and (
       t.driver_id = app.current_driver_id()
       or exists (
         select 1 from public.trip_drivers td
          where td.trip_id = t.id and td.driver_id = app.current_driver_id()
       )
     );

create table if not exists public.vehicle_odometer (
  id          bigint generated by default as identity primary key,
  vehicle_id  bigint not null references public.vehicles (id) on delete cascade,
  driver_id   bigint not null references public.drivers (id) on delete cascade,
  reading_km  integer not null check (reading_km >= 0),
  /* วันที่ตามเวลาไทย ไม่ใช่ UTC — คนขับออกรถตีห้า ซึ่ง UTC ยังเป็นเมื่อวาน
     ถ้าใช้วันของ UTC เลขไมล์ของเช้าวันนี้จะไปนับเป็นของเมื่อวานทั้งกะ */
  reading_date date not null default (timezone('Asia/Bangkok', now()))::date,
  taken_at    timestamptz not null default now(),
  /* เที่ยวที่คนขับกำลังจะวิ่งตอนกรอก — ไว้ตอบว่าเลขนี้มาจากงานไหน ไม่ใช่กุญแจ
     ไม่ผูกเป็น not null เพราะเลขไมล์เป็นของรถ ไม่ใช่ของเที่ยว */
  trip_id     bigint references public.trips (id) on delete set null,
  created_at  timestamptz not null default now(),
  unique (vehicle_id, driver_id, reading_date)
);

create index if not exists vehicle_odometer_vehicle_idx
  on public.vehicle_odometer (vehicle_id, reading_date desc);

alter table public.vehicle_odometer enable row level security;

drop policy if exists vehicle_odometer_read on public.vehicle_odometer;
create policy vehicle_odometer_read on public.vehicle_odometer
  for select using (
    app.has_perm('dispatch.view')
    or app.has_perm('vehicles.write')
    /* คนขับต้องเห็นของตัวเอง ไม่งั้นจอบอกไม่ได้ว่าวันนี้กรอกไปแล้ว */
    or driver_id = app.current_driver_id()
  );

/* เขียนผ่าน log_odometer เท่านั้น — ด่านเรื่องเลขถอยหลังอยู่ในฟังก์ชัน
   เปิดให้ insert ตรงคือเปิดช่องให้เลขไมล์ลดลงได้โดยไม่มีใครรู้ */
drop policy if exists vehicle_odometer_write on public.vehicle_odometer;
create policy vehicle_odometer_write on public.vehicle_odometer
  for all using (app.has_perm('vehicles.write')) with check (app.has_perm('vehicles.write'));

/* ---------------------------------------------------------------
   log_odometer — บันทึกเลขไมล์ของวันนี้

   แก้ของวันเดียวกันซ้ำได้ (กรอกผิดหลักแล้วรู้ตัวทันที) แต่ข้ามวันแล้วแก้ไม่ได้
   ผ่านทางนี้ ต้องให้ออฟฟิศแก้ ซึ่งเป็นเรื่องที่ควรมีคนเห็น
   --------------------------------------------------------------- */
create or replace function public.log_odometer(p_vehicle_id bigint, p_reading_km integer)
returns json
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_me    bigint := app.current_driver_id();
  v_today date   := (timezone('Asia/Bangkok', now()))::date;
  v_last  integer;
  v_trip  bigint;
begin
  if not app.has_perm('myjobs.progress') then
    raise exception 'ไม่มีสิทธิ์บันทึกเลขไมล์' using errcode = '42501';
  end if;
  if v_me is null then
    raise exception 'บัญชีนี้ไม่ได้ผูกกับคนขับ' using errcode = 'P0001';
  end if;
  if p_reading_km is null or p_reading_km < 0 then
    raise exception 'เลขไมล์ไม่ถูกต้อง' using errcode = 'P0001';
  end if;

  /* ต้องเป็นรถที่คนขับมีงานอยู่จริง ไม่ใช่รถคันไหนก็ได้ในระบบ
     ไม่จำกัดว่าต้องเป็นเที่ยวของวันนี้ เพราะเที่ยวข้ามคืนมีจริง */
  select t.id into v_trip
    from public.trips t
   where t.vehicle_id = p_vehicle_id
     and t.status <> 'cancelled'
     and (t.driver_id = v_me
          or exists (select 1 from public.trip_drivers td
                      where td.trip_id = t.id and td.driver_id = v_me))
   order by case when t.status = 'in_progress' then 0
                 when t.status = 'planned' then 1 else 2 end,
            t.id desc
   limit 1;

  if v_trip is null then
    raise exception 'ไม่ได้รับงานของรถคันนี้' using errcode = '42501';
  end if;

  /* เลขไมล์เดินหน้าอย่างเดียว — เลขที่ต่ำกว่าครั้งก่อนแปลว่าอ่านผิดหลัก
     หรือกรอกผิดคัน ทั้งสองอย่างต้องหยุดตรงนี้ ไม่ใช่ไปโผล่ตอนคิดค่าน้ำมันสิ้นเดือน
     ยกเว้นของวันเดียวกันที่กำลังจะทับ ซึ่งคือการแก้เลขที่เพิ่งกรอกผิด */
  select max(reading_km) into v_last
    from public.vehicle_odometer
   where vehicle_id = p_vehicle_id
     and reading_date < v_today;

  if v_last is not null and p_reading_km < v_last then
    raise exception 'เลขไมล์น้อยกว่าครั้งก่อน (%) — อ่านเลขบนหน้าปัดอีกครั้ง', v_last
      using errcode = 'P0001';
  end if;

  insert into public.vehicle_odometer (vehicle_id, driver_id, reading_km, reading_date, trip_id)
  values (p_vehicle_id, v_me, p_reading_km, v_today, v_trip)
  on conflict (vehicle_id, driver_id, reading_date)
    do update set reading_km = excluded.reading_km,
                  taken_at   = now(),
                  trip_id    = excluded.trip_id;

  return json_build_object('vehicle_id', p_vehicle_id, 'reading_km', p_reading_km, 'date', v_today);
end;
$function$;

/* ---------------------------------------------------------------
   odometer_status — จอต้องรู้ก่อนเปิดโมดัลว่าวันนี้กรอกไปหรือยัง

   คืนเลขครั้งก่อนมาด้วย เพื่อให้จอบอกได้ว่า "ครั้งก่อน 128,400" ซึ่งเป็นตัวเลข
   ที่ทำให้คนขับรู้ทันทีว่าตัวเองอ่านผิดหลัก ก่อนจะกดบันทึก
   --------------------------------------------------------------- */
create or replace function public.odometer_status(p_vehicle_id bigint)
returns json
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_me    bigint := app.current_driver_id();
  v_today date   := (timezone('Asia/Bangkok', now()))::date;
  v_now   integer;
  v_last  integer;
begin
  if not app.has_perm('myjobs.view') then
    raise exception 'ไม่มีสิทธิ์ดูเลขไมล์' using errcode = '42501';
  end if;

  select reading_km into v_now
    from public.vehicle_odometer
   where vehicle_id = p_vehicle_id and driver_id = v_me and reading_date = v_today;

  select reading_km into v_last
    from public.vehicle_odometer
   where vehicle_id = p_vehicle_id and reading_date < v_today
   order by reading_date desc, id desc
   limit 1;

  return json_build_object('logged_today', v_now is not null,
                           'reading_km', v_now,
                           'last_km', v_last);
end;
$function$;

/* ---------------------------------------------------------------
   ค่าทางด่วน — เก็บตอนกดจบงานกลับถึงคลัง

   trips.toll_cost มีอยู่แล้วตั้งแต่ต้น แต่ view ฝั่งคนขับตัดคอลัมน์เงินออกทั้งหมด
   ตั้งใจ (คนขับไม่ต้องเห็นค่าจ้างของเที่ยว) การให้คนขับกรอกจึงต้องผ่านฟังก์ชัน
   ไม่ใช่เปิด view ให้เห็นเงินทั้งก้อนเพื่อกรอกช่องเดียว
   --------------------------------------------------------------- */
alter table public.trips
  add column if not exists toll_reported_at timestamptz,
  add column if not exists toll_reported_by bigint references public.users(id) on delete set null;

comment on column public.trips.toll_reported_at is
  'คนขับยืนยันค่าทางด่วนของเที่ยวนี้เมื่อไหร่ — null คือยังไม่เคยถาม ต่างจาก toll_cost = 0 ที่แปลว่าถามแล้วและไม่มีจริง';

/* finish_return เดิมรับ p_trip_id ตัวเดียว ต้อง drop ก่อนแล้วสร้างใหม่พร้อม default
   ปล่อยไว้สองตัวคือ PostgREST เจอสองแบบแล้วเลือกไม่ถูกตอนเรียกด้วยอาร์กิวเมนต์เดียว */
drop function if exists public.finish_return(bigint);

create or replace function public.finish_return(p_trip_id bigint, p_toll_cost numeric default null)
returns json
language plpgsql
security definer
set search_path to 'public', 'auth'
as $function$
declare
  v_me      bigint := app.current_driver_id();
  v_user    bigint := app.current_user_id();
  v_primary bigint;
  v_trip    public.trips;
  v_nopod   integer;
begin
  if not app.has_perm('myjobs.progress') then
    raise exception 'ไม่มีสิทธิ์อัปเดตงาน' using errcode = '42501';
  end if;

  select * into v_trip from public.trips where id = p_trip_id;
  if not found then
    raise exception 'ไม่พบเที่ยวนี้' using errcode = 'P0002';
  end if;

  v_primary := app.trip_primary_driver(p_trip_id);
  if v_primary is distinct from v_me then
    raise exception 'ปิดเที่ยวได้เฉพาะคนขับหลัก' using errcode = 'P0001';
  end if;

  if p_toll_cost is not null and p_toll_cost < 0 then
    raise exception 'ค่าทางด่วนติดลบไม่ได้' using errcode = 'P0001';
  end if;

  -- นับใบที่ส่งแล้วแต่ยังไม่มีหลักฐานพร้อมรูป — เงื่อนไขเดียวกับใน complete_trip
  select count(*) into v_nopod
    from public.orders o
   where o.trip_id = p_trip_id
     and o.status = 'delivered'
     and not exists (
       select 1 from public.pod p
        join public.pod_photos f on f.pod_id = p.id
       where p.order_id = o.id
     );

  if v_nopod > 0 then
    raise exception 'ยังเก็บหลักฐานไม่ครบ เหลืออีก % ใบ — เก็บให้ครบก่อนจบงาน', v_nopod
      using errcode = 'P0001';
  end if;

  update public.trips
     set status = 'completed',
         returned_at = coalesce(returned_at, now()),
         /* ไม่แตะ toll_cost ถ้าไม่ได้ส่งมา — ออฟฟิศอาจกรอกไว้ก่อนแล้ว
            การเขียนทับด้วย 0 เพราะจอไม่ได้ถาม คือลบตัวเลขที่มีคนกรอกมาแล้ว */
         toll_cost = case when p_toll_cost is null then toll_cost else p_toll_cost end,
         toll_reported_at = case when p_toll_cost is null then toll_reported_at else now() end,
         toll_reported_by = case when p_toll_cost is null then toll_reported_by else v_user end
   where id = p_trip_id and status = 'returning';

  if not found then
    raise exception 'เที่ยวนี้ไม่ได้อยู่ระหว่างกลับคลัง' using errcode = 'P0001';
  end if;

  /* คืนของตรงนี้แทน ไม่ใช่ตอนปิดงานที่ร้านสุดท้าย */
  update public.vehicles set status = 'available' where id = v_trip.vehicle_id;
  update public.drivers set status = 'available'
   where id in (select driver_id from public.trip_drivers where trip_id = p_trip_id)
      or id = v_trip.driver_id
      or id = v_me;

  /* ค่าทางด่วนคือเงิน ต้องตอบได้ว่าใครใส่ตัวเลขนี้และใส่เมื่อไหร่ */
  if p_toll_cost is not null then
    insert into public.evidence_audit_log (actor_user_id, action, trip_no, order_id, detail)
    values (v_user, 'toll_reported', v_trip.trip_no, null,
            json_build_object('toll_cost', p_toll_cost, 'by', 'driver'));
  end if;

  return json_build_object('trip_id', p_trip_id, 'trip_no', v_trip.trip_no);
end;
$function$;

revoke all on function public.log_odometer(bigint, integer) from public;
revoke all on function public.odometer_status(bigint) from public;
grant execute on function public.finish_return(bigint, numeric) to authenticated;
grant execute on function public.log_odometer(bigint, integer) to authenticated;
grant execute on function public.odometer_status(bigint) to authenticated;
