-- Permission groups: role defaults, explicit per-user overrides, and audit history.
-- Existing allowed=true rows are preserved as explicit allow overrides.

alter table public.user_permissions
  add column if not exists mode text;

update public.user_permissions
set mode = case when allowed then 'allow' else 'deny' end
where mode is null;

alter table public.user_permissions
  alter column mode set default 'allow';

alter table public.user_permissions
  drop constraint if exists user_permissions_mode_check;

alter table public.user_permissions
  add constraint user_permissions_mode_check check (mode in ('allow', 'deny'));

create table if not exists public.permission_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id bigint references public.users(id) on delete set null,
  target_user_id bigint references public.users(id) on delete set null,
  role text,
  action text not null,
  permission text,
  before_value text,
  after_value text,
  reason text,
  created_at timestamptz not null default now()
);

create or replace function public.audit_user_security_change()
returns trigger language plpgsql security definer set search_path = public
as $$
declare v_actor_id bigint;
begin
  select id into v_actor_id from public.users where auth_id = auth.uid();
  if tg_op = 'UPDATE' and old.role is distinct from new.role then
    insert into public.permission_audit_log(actor_user_id,target_user_id,action,before_value,after_value)
    values (v_actor_id,new.id,'user_role_changed',old.role::text,new.role::text);
  elsif tg_op = 'UPDATE' and old.is_active is distinct from new.is_active then
    insert into public.permission_audit_log(actor_user_id,target_user_id,action,before_value,after_value)
    values (v_actor_id,new.id,case when new.is_active then 'user_activated' else 'user_revoked' end,old.is_active::text,new.is_active::text);
  elsif tg_op = 'DELETE' then
    insert into public.permission_audit_log(actor_user_id,target_user_id,action,before_value)
    values (v_actor_id,old.id,'user_deleted',old.username);
  end if;
  return coalesce(new, old);
end;
$$;

drop trigger if exists users_security_audit on public.users;
create trigger users_security_audit after update or delete on public.users
for each row execute function public.audit_user_security_change();

alter table public.permission_audit_log enable row level security;

-- Permission administration is role-protected, not permission-protected.
-- This closes the old escalation path where a non-admin could grant users.manage to self.
drop policy if exists user_perms_manage_all on public.user_permissions;
drop policy if exists user_permissions_admin_all on public.user_permissions;
create policy user_permissions_admin_all on public.user_permissions
  for all to authenticated
  using (exists (select 1 from public.users u where u.auth_id = auth.uid() and u.role = 'admin' and u.is_active))
  with check (exists (select 1 from public.users u where u.auth_id = auth.uid() and u.role = 'admin' and u.is_active));

drop policy if exists permission_audit_admin_read on public.permission_audit_log;
create policy permission_audit_admin_read on public.permission_audit_log
  for select to authenticated
  using (exists (select 1 from public.users u where u.auth_id = auth.uid() and u.role = 'admin' and u.is_active));

create or replace function public.effective_permissions(p_user_id bigint)
returns table(permission text, allowed boolean, source text)
language sql stable security definer set search_path = public
as $$
  select p.permission,
         coalesce(o.mode = 'allow', rp.permission is not null) as allowed,
         case when o.mode is not null then 'user' else 'group' end as source
  from public.permissions p
  left join public.users u on u.id = p_user_id
  left join public.role_permissions rp on rp.role = u.role and rp.permission = p.permission
  left join public.user_permissions o on o.user_id = p_user_id and o.permission = p.permission;
$$;

create or replace function public.admin_save_user_permission(
  p_user_id bigint, p_permission text, p_mode text, p_reason text default null
)
returns void language plpgsql security definer set search_path = public
as $$
declare
  v_actor public.users;
  v_before text;
begin
  select * into v_actor from public.users where auth_id = auth.uid() and is_active;
  if v_actor.role is distinct from 'admin' then raise exception 'admin only'; end if;
  if p_mode not in ('inherit','allow','deny') then raise exception 'invalid permission mode'; end if;
  if not exists (select 1 from public.permissions where permission = p_permission) then raise exception 'unknown permission'; end if;
  select mode into v_before from public.user_permissions where user_id = p_user_id and permission = p_permission;
  if p_mode = 'inherit' then
    delete from public.user_permissions where user_id = p_user_id and permission = p_permission;
  else
    insert into public.user_permissions(user_id, permission, allowed, mode)
    values (p_user_id, p_permission, p_mode = 'allow', p_mode)
    on conflict (user_id, permission) do update set allowed = excluded.allowed, mode = excluded.mode;
  end if;
  insert into public.permission_audit_log(actor_user_id,target_user_id,action,permission,before_value,after_value,reason)
  values (v_actor.id,p_user_id,'user_permission_changed',p_permission,coalesce(v_before,'inherit'),p_mode,p_reason);
end;
$$;

create or replace function public.admin_reset_user_permissions(p_user_id bigint, p_reason text default null)
returns void language plpgsql security definer set search_path = public
as $$
declare v_actor public.users;
begin
  select * into v_actor from public.users where auth_id = auth.uid() and is_active;
  if v_actor.role is distinct from 'admin' then raise exception 'admin only'; end if;
  delete from public.user_permissions where user_id = p_user_id;
  insert into public.permission_audit_log(actor_user_id,target_user_id,action,reason)
  values (v_actor.id,p_user_id,'user_permissions_reset',p_reason);
end;
$$;

create or replace function public.admin_set_role_permission(
  p_role public.user_role, p_permission text, p_allowed boolean, p_reason text default null
)
returns void language plpgsql security definer set search_path = public
as $$
declare v_actor public.users; v_before boolean;
begin
  select * into v_actor from public.users where auth_id = auth.uid() and is_active;
  if v_actor.role is distinct from 'admin' then raise exception 'admin only'; end if;
  if p_role = 'admin' and not p_allowed then raise exception 'admin defaults are protected'; end if;
  if not exists (select 1 from public.permissions where permission = p_permission) then raise exception 'unknown permission'; end if;
  select exists(select 1 from public.role_permissions where role = p_role and permission = p_permission) into v_before;
  if p_allowed then
    insert into public.role_permissions(role,permission) values (p_role,p_permission) on conflict do nothing;
  else
    delete from public.role_permissions where role = p_role and permission = p_permission;
  end if;
  insert into public.permission_audit_log(actor_user_id,role,action,permission,before_value,after_value,reason)
  values (v_actor.id,p_role::text,'role_permission_changed',p_permission,v_before::text,p_allowed::text,p_reason);
end;
$$;

grant execute on function public.effective_permissions(bigint) to authenticated;
grant execute on function public.admin_save_user_permission(bigint,text,text,text) to authenticated;
grant execute on function public.admin_reset_user_permissions(bigint,text) to authenticated;
grant execute on function public.admin_set_role_permission(public.user_role,text,boolean,text) to authenticated;
